import TankStackProvider from "@/components/wrappers/TankStackProvider/TankStackProvider";
import "./globals.css";
import MainWrapp from "@/components/wrappers/mainWrap/MainWrapp";
import { Montserrat } from "next/font/google";
import Head from "next/head";

const montserrat = Montserrat({
	subsets: ["latin"],
	weight: ["400", "500", "600", "800"],
});
export const metadata = {
	title: "Minzifa-Travel.ru",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<Head>
				<meta name='viewport' content='width=device-width' />
			</Head>
			<body className={montserrat.className}>
				<TankStackProvider>
					<MainWrapp>{children}</MainWrapp>
				</TankStackProvider>
			</body>
		</html>
	);
}
